### PR TITLE
Update package information for PyPI publishing

### PR DESCRIPTION
**Pull request by efischer19**
Copied from https://github.com/edx/edx-drf-extensions/blob/master/setup.py#L12-L13, on the advice of https://openedx.atlassian.net/wiki/display/OpenOPS/Publishing+a+Package+to+PyPI+using+Travis.

@doctoryes to review

### CODE REVIEW

**Comment by doctoryes** [comment]
👍

**Comment by efischer19** [comment]
@doctoryes I've also added to this commit slight changes to the package's name (our other PyPI packages all have the `edx-` prefix) and url (now points to this repo)

**Comment by doctoryes** [comment]
Still 👍

**Comment by efischer19** [comment]
@doctoryes, I can't merge this PR (lack of write access), but it's ready to be merged whenever you'd like.

All that remains is to get the edX PyPI account details for package publishing (see [DEVOPS-4431](https://openedx.atlassian.net/browse/DEVOPS-4431)), publish it properly, then test and merge the following IDA PRs:
- [ ] ecommerce: https://github.com/edx/ecommerce/pull/843
- [ ] programs: https://github.com/edx/programs/pull/148
- [ ] analytics-api: https://github.com/edx/edx-analytics-data-api/pull/126
- [ ] insights: https://github.com/edx/edx-analytics-dashboard/pull/500
- [ ] xqueue: https://github.com/edx/xqueue/pull/108
- [ ] credentials: https://github.com/edx/credentials/pull/107
- [ ] discovery: https://github.com/edx/course-discovery/pull/150

**Comment by doctoryes** [comment]
@efischer19 Merged now.

**Pull request merged**
